"""
Brain_Scape — Q&A Engine

Scan-aware conversational query system. The user can ask anything
about the scan. The LLM holds full context of the scan report,
damage map, atlas labels, and metadata when generating answers.

It does NOT hallucinate anatomy — it works from computed atlas
labels and damage scores already generated by the pipeline.
"""

import logging
from typing import Optional

from llm.rag_engine import RAGEngine
from llm.prompt_templates import PromptTemplates

logger = logging.getLogger(__name__)


class QAEngine:
    """
    Scan-aware conversational Q&A system.

    Combines scan analysis context with RAG-retrieved clinical literature
    to produce cited, grounded responses to user questions.
    """

    def __init__(
        self,
        rag_engine: RAGEngine,
        llm_client=None,
        model: str = "gpt-4",
        temperature: float = 0.3,
        max_tokens: int = 2048,
    ):
        """
        Args:
            rag_engine: RAG engine for clinical literature retrieval.
            llm_client: OpenAI or Anthropic client instance.
            model: LLM model identifier.
            temperature: LLM temperature.
            max_tokens: Maximum tokens in response.
        """
        self.rag = rag_engine
        self.llm_client = llm_client
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens

    def answer(
        self,
        question: str,
        scan_analysis: dict,
        voice_audio_b64: Optional[str] = None,
    ) -> dict:
        """
        Answer a question about a scan.

        Args:
            question: User's question about the scan.
            scan_analysis: Full analysis JSON from the pipeline.
            voice_audio_b64: Optional base64-encoded audio for voice queries.

        Returns:
            Dictionary with answer, citations, and confidence.
        """
        # Transcribe voice if audio provided
        if voice_audio_b64:
            question = self._transcribe_audio(voice_audio_b64) or question

        # Retrieve relevant clinical literature
        rag_results = self.rag.retrieve(question)

        # Build context from scan analysis + RAG results
        context = self._build_context(scan_analysis, rag_results)

        # Generate answer using LLM
        prompt = PromptTemplates.qa_prompt(question, context)

        if self.llm_client:
            answer_text = self._call_llm(prompt)
        else:
            answer_text = self._generate_fallback_answer(question, scan_analysis, rag_results)

        # Extract citations from RAG results
        citations = self._extract_citations(rag_results)

        # Compute answer confidence
        confidence = self._compute_answer_confidence(scan_analysis, rag_results)

        result = {
            "question": question,
            "answer": answer_text,
            "citations": citations,
            "confidence": round(confidence, 4),
            "model": self.model,
            "rag_chunks_used": len(rag_results),
        }

        logger.info(
            f"Q&A: '{question[:50]}...' -> {len(answer_text)} chars, "
            f"confidence={confidence:.2f}, citations={len(citations)}"
        )

        return result

    def _build_context(
        self, scan_analysis: dict, rag_results: list[dict]
    ) -> str:
        """Build the full context string for the LLM prompt."""
        context_parts = []

        # Scan analysis context
        context_parts.append("=== SCAN ANALYSIS ===")
        if "regions" in scan_analysis:
            for region in scan_analysis.get("regions", [])[:10]:
                context_parts.append(
                    f"- {region.get('anatomical_name', 'Unknown')}: "
                    f"severity={region.get('severity_label', 'N/A')}, "
                    f"confidence={region.get('confidence', 'N/A')}"
                )

        if "differential_diagnosis" in scan_analysis:
            context_parts.append("\n=== DIFFERENTIAL DIAGNOSIS ===")
            for diag in scan_analysis.get("differential_diagnosis", []):
                context_parts.append(
                    f"- {diag.get('etiology', 'Unknown')}: "
                    f"probability={diag.get('probability', 'N/A')}"
                )

        if "connectivity" in scan_analysis:
            context_parts.append("\n=== CONNECTIVITY ===")
            conn = scan_analysis["connectivity"]
            context_parts.append(
                f"Disrupted networks: {', '.join(conn.get('disrupted_networks', []))}"
            )

        # RAG context
        if rag_results:
            context_parts.append("\n=== CLINICAL LITERATURE ===")
            for i, result in enumerate(rag_results):
                context_parts.append(
                    f"[{i+1}] {result.get('title', 'Untitled')} "
                    f"({result.get('year', 'N/A')}): {result.get('text', '')[:300]}"
                )

        return "\n".join(context_parts)

    def _call_llm(self, prompt: str) -> str:
        """Call the LLM API with the prompt."""
        try:
            response = self.llm_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": PromptTemplates.QA_SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                temperature=self.temperature,
                max_tokens=self.max_tokens,
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error(f"LLM API call failed: {e}")
            return f"Error generating response: {str(e)}"

    def _generate_fallback_answer(
        self,
        question: str,
        scan_analysis: dict,
        rag_results: list[dict],
    ) -> str:
        """Generate a basic answer without LLM (template-based)."""
        question_lower = question.lower()

        # Check for region-related questions
        regions = scan_analysis.get("regions", [])
        damaged_regions = [r for r in regions if r.get("severity_level", 0) >= 2]

        if "damage" in question_lower or "affected" in question_lower:
            if damaged_regions:
                region_names = [r.get("anatomical_name", "Unknown") for r in damaged_regions]
                return (
                    f"Based on the analysis, {len(damaged_regions)} regions show damage: "
                    f"{', '.join(region_names[:5])}. "
                    f"The most severely affected region is {damaged_regions[0].get('anatomical_name', 'unknown')} "
                    f"with {damaged_regions[0].get('severity_label', 'unknown')} severity "
                    f"(confidence: {damaged_regions[0].get('confidence', 'N/A')})."
                )

        if "speech" in question_lower or "language" in question_lower:
            speech_regions = [r for r in regions if "broca" in r.get("anatomical_name", "").lower()
                            or "wernicke" in r.get("anatomical_name", "").lower()
                            or "inferior frontal" in r.get("anatomical_name", "").lower()]
            if speech_regions:
                return (
                    f"Yes, the speech-related region(s) {', '.join(r.get('anatomical_name', '') for r in speech_regions)} "
                    f"are implicated. Severity: {speech_regions[0].get('severity_label', 'N/A')}."
                )
            return "No speech-related regions appear to be affected based on this scan."

        # Generic fallback
        return (
            f"Based on the scan analysis, {len(damaged_regions)} out of {len(regions)} "
            f"regions show damage. For detailed clinical interpretation, "
            f"please consult the full report or ask a more specific question."
        )

    @staticmethod
    def _extract_citations(rag_results: list[dict]) -> list[dict]:
        """Extract citation information from RAG results."""
        citations = []
        for result in rag_results:
            citation = {
                "title": result.get("title", ""),
                "source": result.get("source", ""),
                "year": result.get("year", ""),
                "doi": result.get("doi", ""),
                "relevance_score": result.get("score", 0),
            }
            if citation["title"]:
                citations.append(citation)
        return citations

    @staticmethod
    def _compute_answer_confidence(
        scan_analysis: dict, rag_results: list[dict]
    ) -> float:
        """Compute confidence score for the answer."""
        # Base confidence from scan analysis
        scan_conf = scan_analysis.get("overall_confidence", 0.5)

        # Boost from RAG retrieval
        rag_conf = max((r.get("score", 0) for r in rag_results), default=0.5)

        return 0.6 * scan_conf + 0.4 * rag_conf

    @staticmethod
    def _transcribe_audio(audio_b64: str) -> Optional[str]:
        """Transcribe audio to text using Whisper (Phase 2)."""
        try:
            import whisper
            import base64
            import tempfile

            # Decode base64 audio
            audio_bytes = base64.b64decode(audio_b64)

            # Write to temp file
            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
                f.write(audio_bytes)
                temp_path = f.name

            # Transcribe
            model = whisper.load_model("medium")
            result = model.transcribe(temp_path)

            # Cleanup
            import os
            os.unlink(temp_path)

            return result.get("text", "")

        except ImportError:
            logger.warning("Whisper not available for audio transcription.")
            return None