xychart-beta
  title "Top Regions Frequency Severity GE 2"
  x-axis ["Precentral_R", "Hippocampus_R", "Precentral_L", "Hippocampus_L", "Parietal_Inf_L", "Temporal_Mid_L"]
  y-axis "Frequency" 0 --> 41
  bar [35, 21, 19, 19, 19, 17]
